# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/busra/Documents/Documenten/Leerjaar 2/Blok 7/RETROGAME_GIT/RetroGame-FPGA/Snowshot.srcs/sources_1/ip/rom_bg/rom_bg.xci
# IP: The module: 'rom_bg' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/busra/Documents/Documenten/Leerjaar 2/Blok 7/RETROGAME_GIT/RetroGame-FPGA/Snowshot.srcs/sources_1/ip/rom_bg/rom_bg_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_bg'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/busra/Documents/Documenten/Leerjaar 2/Blok 7/RETROGAME_GIT/RetroGame-FPGA/Snowshot.srcs/sources_1/ip/rom_bg/rom_bg.xci
# IP: The module: 'rom_bg' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/busra/Documents/Documenten/Leerjaar 2/Blok 7/RETROGAME_GIT/RetroGame-FPGA/Snowshot.srcs/sources_1/ip/rom_bg/rom_bg_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_bg'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
