# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Xilinx/Projects/RetroGame-FPGA/RetroGame-FPGA/Snowshot.srcs/sources_1/ip/blk_mem_santa2_back/blk_mem_santa2_back.xci
# IP: The module: 'blk_mem_santa2_back' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/Projects/RetroGame-FPGA/RetroGame-FPGA/Snowshot.srcs/sources_1/ip/blk_mem_santa2_back/blk_mem_santa2_back_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_santa2_back'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Xilinx/Projects/RetroGame-FPGA/RetroGame-FPGA/Snowshot.srcs/sources_1/ip/blk_mem_santa2_back/blk_mem_santa2_back.xci
# IP: The module: 'blk_mem_santa2_back' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/Projects/RetroGame-FPGA/RetroGame-FPGA/Snowshot.srcs/sources_1/ip/blk_mem_santa2_back/blk_mem_santa2_back_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_santa2_back'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
