# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/cnst.xdc

# IP: ip/clk_vga/clk_vga.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_vga || ORIG_REF_NAME==clk_vga} -quiet] -quiet
