# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/busra/Documents/Documenten/Leerjaar 2/Blok 7/RETROGAME_GIT_NEW/RetroGame-FPGA/Snowshot.srcs/sources_1/ip/blk_mem_tran/blk_mem_tran.xci
# IP: The module: 'blk_mem_tran' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/busra/Documents/Documenten/Leerjaar 2/Blok 7/RETROGAME_GIT_NEW/RetroGame-FPGA/Snowshot.srcs/sources_1/ip/blk_mem_tran/blk_mem_tran_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_tran'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/busra/Documents/Documenten/Leerjaar 2/Blok 7/RETROGAME_GIT_NEW/RetroGame-FPGA/Snowshot.srcs/sources_1/ip/blk_mem_tran/blk_mem_tran.xci
# IP: The module: 'blk_mem_tran' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/busra/Documents/Documenten/Leerjaar 2/Blok 7/RETROGAME_GIT_NEW/RetroGame-FPGA/Snowshot.srcs/sources_1/ip/blk_mem_tran/blk_mem_tran_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_tran'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
